version: "3.2"

services:
    # web:
    #     build: .
    #     command: npm start
    #     ports:
    #     - "3000:3000"
    #     environment:
    #     - DB_HOST=postgresql
    #     - DB_PORT=5432
    #     - DB_PW=my_pass
    #     - DB_USER=my_user
    #     - DB_NAME=default
    #     - JWT_SECRET=secret
    #     depends_on:
    #     - postgresql

    # Start local Postgres
    postgresql:
        image: 'bitnami/postgresql:latest'
        ports:
            - '5432:5432'
        environment:
            - POSTGRESQL_USERNAME=my_user
            - POSTGRESQL_PASSWORD=my_pass
            - POSTGRESQL_DATABASE=backend
        volumes:
            - './bitnami/postgresql'